$apiKey= "API-XXXXXXXXXXXXXXXXXXXXXXXXX"
$octopusUrl = "http://cd.XXXXXXXXXXXXXXXXXXXXXXXXX.com"
$environmentName = "IaC XXXXXXXXXXXXXXXXXXXXXXXXX"
$fingerprint ="XXXXXXXXXXXXXXXXXXXXXXXXX"
$accountName = "XXXXXXXXXXXXXXXXXXXXXXXXXAzure EA"

$headers = @{"X-Octopus-ApiKey"=$apiKey} 
$headers.Add( "Content-Type","application/json");

$environments = Invoke-RestMethod $octopusUrl"/api/environments/all" -Headers $headers -Method Get
$theEnvironment = $environments | ? { $_.Name -eq $environmentName }

$accounts = Invoke-RestMethod $octopusUrl"/api/accounts/all" -Headers $headers -Method Get
$theAccount = $accounts | ? { $_.Name -eq $accountName }


#Config
$OctopusAPIkey = "API-XXXXXXXXXXXXXXXXXXXXXXXXX" #API Key to authenticate in Octopus
$OctopusURL = "http://cd.XXXXXXXXXXXXXXXXXXXXXXXXX.com" #Octopus server url

$TentacleURL = "Http://MyMachineFQDN" #Tentacle URL. Remember it must be https. i.e "https://localhost","http://192.168.1.12","Http://MyMachineFQDN"
$TentaclePort = "1093" #Port the Listening Tentacle will use to comunicate with the Octopus server
$TentacleThumbprint = "897980CEDEC84FB10EAE8516376F9E820BF5361C" #Tentacle Thumbprint
$TentacleName = "TentName" #Tentacle name
$TentacleRoles = "XXXXXXXXXXXXXXXXXXXXXXXXX" #Tentacle role. It can be a collection 
$EnvironmentIDs = $theEnvironment.Id #IDs of the Environments where the Tentacle will be registered. It can be a collection

$apiKey= "API-NV2SBJW82VEF1AASIHZBUN3GONC"
$octopusUrl = "http://cd.XXXXXXXXXXXXXXXXXXXXXXXXX.com"
$environmentName = "IaC Generated by TC Build"
$fingerprint ="XXXXXXXXXXXXXXXXXXXXXXXXX"
$accountName = "Azure Service Principle - XXXXXXXXXXXXXXXXXXXXXXXXX Azure EA"

$headers = @{"X-Octopus-ApiKey"=$apiKey} 
$headers.Add( "Content-Type","application/json");
##Process
$header = @{ "X-Octopus-ApiKey" = $octopusAPIKey }

$body = @{ Endpoint = @{
                        CommunicationStyle = "TentaclePassive" #This will only work for Listening Tentacles
                        Thumbprint = $TentacleThumbprint
                        Uri = "$tentacleURL`:$TentaclePort/"
                        }
            EnvironmentIDs = @($EnvironmentIDs)
            Name = $TentacleName
            Roles = @($TentacleRoles)
            Status = "Unknown"
            IsDisabled = $false
        } | ConvertTo-Json -Depth 10

Invoke-RestMethod "$OctopusURL/api/machines" -Headers $header -Method Post -Body $body